name: Multi-Branch CI/CD Pipeline

on:
  push:
    branches: [ "dev", "main" ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: pip install fastapi uvicorn

    - name: Unit Tests (Example)
      run: echo "No tests configured"

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .
        args: >
         -Dsonar.projectKey=malikahsanawan_Multi-Branch-CI-CD-Pipeline-with-GitHub-Actions
         -Dsonar.organization=malikahsanawan
         -Dsonar.sources=.
         -Dsonar.host.url=https://sonarcloud.io
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        #SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_HOST_URL: https://sonarcloud.io

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/demo-ci:${{ github.sha }} .

    - name: Trivy Scan
      run: trivy image ${{ secrets.DOCKER_USERNAME }}/demo-ci:${{ github.sha }}

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/demo-ci:${{ github.sha }}

  deploy:
    needs: build-test-scan
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Dev / Prod
      run: |
        if [[ "${GITHUB_REF##*/}" == "dev" ]]; then
            echo "Deploying to DEV server..."
        else
            echo "Deploying to PROD server..."
        fi

